/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    brands: Brand;
    products: Product;
    'product-entries': ProductEntry;
    'product-comments': ProductComment;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'product-entries': ProductEntriesSelect<false> | ProductEntriesSelect<true>;
    'product-comments': ProductCommentsSelect<false> | ProductCommentsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  sourceUrl?: string | null;
  fileUrl: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  legacyId?: number | null;
  name: string;
  slug: string;
  logoUrl?: string | null;
  description?: string | null;
  isVisible?: boolean | null;
  sort?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  legacyId: number;
  name: string;
  slug: string;
  englishName?: string | null;
  brief?: string | null;
  introHtml?: string | null;
  brand?: (number | null) | Brand;
  primaryImageUrl?: string | null;
  gallery?:
    | {
        imageUrl: string;
        id?: string | null;
      }[]
    | null;
  pricing?: {
    price?: number | null;
    marketPrice?: number | null;
    costPrice?: number | null;
  };
  inventory?: {
    stock?: number | null;
    barcode?: string | null;
    skuCode?: string | null;
  };
  specifications?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  stats?: {
    commentsCount?: number | null;
    viewCount?: number | null;
    buyCount?: number | null;
  };
  showOnHome?: boolean | null;
  isMarketable?: boolean | null;
  isRecommend?: boolean | null;
  isHot?: boolean | null;
  sort?: number | null;
  /**
   * 保留旧库参数原始内容，方便后续继续映射。
   */
  legacyParametersRaw?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-entries".
 */
export interface ProductEntry {
  id: number;
  title: string;
  slug: string;
  type: 'community' | 'feed' | 'review';
  product: number | Product;
  excerpt?: string | null;
  content?: string | null;
  authorName?: string | null;
  /**
   * 使用 ISO 时间字符串，先保留排序和显示，减轻后台日期组件体积。
   */
  publishedAt?: string | null;
  isVisible?: boolean | null;
  legacyId?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-comments".
 */
export interface ProductComment {
  id: number;
  product: number | Product;
  content: string;
  authorName: string;
  authorEmail?: string | null;
  authorUser?: (number | null) | User;
  source: 'guest' | 'user';
  isVisible?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'product-entries';
        value: number | ProductEntry;
      } | null)
    | ({
        relationTo: 'product-comments';
        value: number | ProductComment;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  sourceUrl?: T;
  fileUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  legacyId?: T;
  name?: T;
  slug?: T;
  logoUrl?: T;
  description?: T;
  isVisible?: T;
  sort?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  legacyId?: T;
  name?: T;
  slug?: T;
  englishName?: T;
  brief?: T;
  introHtml?: T;
  brand?: T;
  primaryImageUrl?: T;
  gallery?:
    | T
    | {
        imageUrl?: T;
        id?: T;
      };
  pricing?:
    | T
    | {
        price?: T;
        marketPrice?: T;
        costPrice?: T;
      };
  inventory?:
    | T
    | {
        stock?: T;
        barcode?: T;
        skuCode?: T;
      };
  specifications?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  stats?:
    | T
    | {
        commentsCount?: T;
        viewCount?: T;
        buyCount?: T;
      };
  showOnHome?: T;
  isMarketable?: T;
  isRecommend?: T;
  isHot?: T;
  sort?: T;
  legacyParametersRaw?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-entries_select".
 */
export interface ProductEntriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  type?: T;
  product?: T;
  excerpt?: T;
  content?: T;
  authorName?: T;
  publishedAt?: T;
  isVisible?: T;
  legacyId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-comments_select".
 */
export interface ProductCommentsSelect<T extends boolean = true> {
  product?: T;
  content?: T;
  authorName?: T;
  authorEmail?: T;
  authorUser?: T;
  source?: T;
  isVisible?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteTitle: string;
  siteDescription?: string | null;
  siteName?: string | null;
  logoMark?: string | null;
  logoImageUrl?: string | null;
  homeHeroTitle: string;
  homeHeroSubtitle?: string | null;
  browseCollectionLabel?: string | null;
  navCollectionLabel?: string | null;
  navBrandsLabel?: string | null;
  navCommunityLabel?: string | null;
  navFeedLabel?: string | null;
  navAdminLabel?: string | null;
  collectionSearchPlaceholder?: string | null;
  collectionAllLabel?: string | null;
  collectionFormatLabel?: string | null;
  collectionPriceLabel?: string | null;
  collectionNewestLabel?: string | null;
  homeHowButtonLabel?: string | null;
  homeWhyButtonLabel?: string | null;
  homeHowDialogTitle?: string | null;
  homeHowDialogSubtitle?: string | null;
  homeHowDialogItems?:
    | {
        glyph: string;
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  homeWhyDialogTitle?: string | null;
  homeWhyDialogSubtitle?: string | null;
  homeWhyDialogParagraphs?:
    | {
        content: string;
        id?: string | null;
      }[]
    | null;
  turnstileEnabled?: boolean | null;
  /**
   * 前台会使用这个公开 Key 渲染验证码。
   */
  turnstileSiteKey?: string | null;
  /**
   * 提交评论时，服务端会用这个密钥向 Cloudflare 校验验证码。
   */
  turnstileSecretKey?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteTitle?: T;
  siteDescription?: T;
  siteName?: T;
  logoMark?: T;
  logoImageUrl?: T;
  homeHeroTitle?: T;
  homeHeroSubtitle?: T;
  browseCollectionLabel?: T;
  navCollectionLabel?: T;
  navBrandsLabel?: T;
  navCommunityLabel?: T;
  navFeedLabel?: T;
  navAdminLabel?: T;
  collectionSearchPlaceholder?: T;
  collectionAllLabel?: T;
  collectionFormatLabel?: T;
  collectionPriceLabel?: T;
  collectionNewestLabel?: T;
  homeHowButtonLabel?: T;
  homeWhyButtonLabel?: T;
  homeHowDialogTitle?: T;
  homeHowDialogSubtitle?: T;
  homeHowDialogItems?:
    | T
    | {
        glyph?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  homeWhyDialogTitle?: T;
  homeWhyDialogSubtitle?: T;
  homeWhyDialogParagraphs?:
    | T
    | {
        content?: T;
        id?: T;
      };
  turnstileEnabled?: T;
  turnstileSiteKey?: T;
  turnstileSecretKey?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}